name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clean install
        run: |
          npm install
          npm install @capacitor/android

      - name: Build web app
        run: npm run build

      - name: Recreate Android platform
        run: |
          npx cap add android
          npx cap sync android

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Give permission
        run: chmod +x android/gradlew

      - name: Build APK
        run: cd android && ./gradlew assembleDebug
